---
- name: Add 'serj' user
  user:
      name: serj
      shell: /bin/bash
      home: /home/serj
      append: yes

- name: Copy ssh pubkey
  authorized_key:
      user: serj
      key: "{{ lookup('file', '/home/serj/.ssh/id_rsa.pub') }}"

- name: Add "serj" to sudoers
  lineinfile:
      dest: /etc/sudoers
      line: "serj ALL=(ALL)   NOPASSWD: ALL" 
      validate: 'visudo -cf %s'
